package io.ledgerlens.app.ui

class Strings(private val language: String) {
    fun explain(error: String): String = when {
        error.contains("Unused receiving address gap reached") -> get("receiveGap")
        error.contains("Receiving address scan limit reached") -> get("receiveLimit")
        error.contains("api.trongrid.io") && (error.contains("HTTP 429") || error.contains("HTTP 403") || error.contains("HTTP 401")) -> get("tronLimited") + "\n" + error
        error.contains("binance") -> get("binanceUnavailable") + "\n" + error
        else -> error
    }
    operator fun get(key: String): String {
        val row = rows[key] ?: return key
        return row[when(language) { "zh-CN" -> 1; "en" -> 2; else -> 0 }]
    }
    companion object {
        private val rows = mapOf(
            "overview" to listOf("資產", "资产", "Portfolio"),
            "accounts" to listOf("帳戶", "账户", "Accounts"),
            "settings" to listOf("設定", "设置", "Settings"),
            "watchOnly" to listOf("Ledger 硬體錢包", "Ledger 硬件钱包", "LEDGER HARDWARE WALLET"),
            "send" to listOf("傳送", "发送", "Send"),
            "pendingAccount" to listOf("此帳戶有待確認或送出狀態未知的交易。請先查詢狀態，再移除帳戶。", "此账户有待确认或发送状态未知的交易。请先查询状态，再移除账户。", "This account has a pending or uncertain transaction. Check its status before removing the account."),
            "receive" to listOf("接收", "接收", "Receive"),
            "receiveQr" to listOf("主網收款地址 QR 碼", "主网收款地址二维码", "Mainnet receiving address QR code"),
            "receiveHint" to listOf("地址屬於同一個 Ledger 帳戶，舊地址仍可收款。請確認主網與資產；建議先在 Ledger 核對目前地址。", "地址属于同一个 Ledger 账户，旧地址仍可收款。请确认主网与资产；建议先在 Ledger 核对当前地址。", "Addresses belong to the same Ledger account. Previous addresses remain valid. Check the mainnet and asset; verify the displayed address on Ledger."),
            "newReceive" to listOf("產生新收款地址", "生成新收款地址", "Generate new receiving address"),
            "receiveGap" to listOf("已有太多連續未使用的收款地址。請先使用已產生的地址收款，再更新持倉後重試。", "已有太多连续未使用的收款地址。请先使用已生成的地址收款，再更新持仓后重试。", "Too many consecutive unused receiving addresses. Receive funds at an existing address, refresh holdings, then retry."),
            "receiveNumber" to listOf("收款地址", "收款地址", "Receiving address"),
            "previousReceive" to listOf("上一個收款地址", "上一个收款地址", "Previous receiving address"),
            "nextReceive" to listOf("下一個收款地址", "下一个收款地址", "Next receiving address"),
            "btcNewReceiveHint" to listOf("從帳戶公鑰衍生，私鑰留在 Ledger。新增時查詢 BTC 紀錄並跳過已使用地址。", "从账户公钥派生，私钥留在 Ledger。新增时查询 BTC 记录并跳过已使用地址。", "Derived from the account public key; private keys stay on Ledger. New addresses skip those with Bitcoin transaction history."),
            "adaNewReceiveHint" to listOf("從帳戶公鑰衍生下一個地址，不額外查詢 Cardano API；ADA 與 NIGHT 可使用同一地址。", "从账户公钥派生下一个地址，不额外查询 Cardano API；ADA 与 NIGHT 可使用同一地址。", "Derives the next address without additional Cardano API calls. ADA and NIGHT share the address."),
            "singleReceiveHint" to listOf("ETH／TRON 每個帳戶使用同一地址；若要另一個地址，請連接 Ledger 並匯入新的帳戶序號。", "ETH／TRON 每个账户使用同一地址；如需另一个地址，请连接 Ledger 并导入新的账户序号。", "ETH/TRON use one address per account. For another address, connect Ledger and import a new account index."),
            "receiveLimit" to listOf("已到收款地址掃描上限，請提高設定中的掃描上限後重試。", "已到收款地址扫描上限，请提高设置中的扫描上限后重试。", "Receiving address scan limit reached. Increase the scan limit in Settings and retry."),
            "copied" to listOf("已複製", "已复制", "Copied"),
            "share" to listOf("分享地址", "分享地址", "Share address"),
            "verifyAddress" to listOf("在 Ledger 核對地址", "在 Ledger 核对地址", "Verify address on Ledger"),
            "addressVerified" to listOf("Ledger 顯示的地址與此帳戶一致。", "Ledger 显示的地址与此账户一致。", "The address shown on Ledger matches this account."),
            "from" to listOf("來源地址", "来源地址", "From"),
            "recipient" to listOf("收款地址", "收款地址", "Recipient address"),
            "paste" to listOf("貼上地址", "粘贴地址", "Paste address"),
            "scanQr" to listOf("掃描 QR", "扫描二维码", "Scan QR"),
            "amount" to listOf("數量", "数量", "Amount"),
            "maximum" to listOf("最大可傳送 · 預留費用", "最大可发送 · 预留费用", "Maximum · reserve fees"),
            "prepareHint" to listOf("估算前會重新查詢鏈上資產。代幣轉帳仍需原生幣支付網路費；BTC 僅使用已確認輸出。", "估算前会重新查询链上资产。代币转账仍需原生币支付网络费；BTC 仅使用已确认输出。", "Refreshes chain data before estimating. Tokens need the native coin for fees. BTC uses confirmed outputs only."),
            "estimateReview" to listOf("估算費用並檢查交易", "估算费用并检查交易", "Estimate fees and review"),
            "reviewTransaction" to listOf("確認交易內容", "确认交易内容", "Review transaction"),
            "networkFee" to listOf("預估網路費／預留上限", "预估网络费／预留上限", "Estimated network fee / reserved cap"),
            "attachedAda" to listOf("隨 NIGHT 轉帳附帶 ADA（收款方收到）", "随 NIGHT 转账附带 ADA（收款方收到）", "ADA attached to NIGHT (received by recipient)"),
            "totalDebit" to listOf("總扣款／預留上限", "总扣款／预留上限", "Total debit / reserved cap"),
            "reviewWarning" to listOf("請核對完整地址與金額。手機確認後，在 Ledger 上檢查並實體核准；簽名驗證成功後自動廣播。估算 5 分鐘後失效。", "请核对完整地址与金额。手机确认后，在 Ledger 上检查并实体验证；签名验证成功后自动广播。估算 5 分钟后失效。", "Check the full address and amount. After phone confirmation, review and approve on Ledger. Verified signatures are broadcast automatically. Estimate expires after 5 minutes."),
            "confirmOnLedger" to listOf("確認並交由 Ledger 簽署", "确认并交由 Ledger 签署", "Confirm and sign on Ledger"),
            "edit" to listOf("修改交易", "修改交易", "Edit transaction"),
            "preparing" to listOf("正在查詢資產與估算費用…", "正在查询资产与估算费用…", "Refreshing balances and estimating fees…"),
            "ledgerApproval" to listOf("請開啟相同幣種的 Ledger App，核對交易並在 Ledger 上確認…", "请打开相同币种的 Ledger App，核对交易并在 Ledger 上确认…", "Open the matching coin app, review and approve the transaction on Ledger…"),
            "broadcasting" to listOf("簽名已驗證，正在廣播…", "签名已验证，正在广播…", "Signature verified. Broadcasting…"),
            "submittedHint" to listOf("已保存交易 ID。請在「帳戶」查看廣播與鏈上確認狀態；首次成功確認後更新餘額。", "已保存交易 ID。请在「账户」查看广播与链上确认状态；首次成功确认后更新余额。", "Transaction ID saved. View submission and confirmation status in Accounts. Balances refresh after the first successful confirmation."),
            "transactions" to listOf("交易記錄", "交易记录", "Transactions"),
            "checkStatus" to listOf("查詢交易狀態", "查询交易状态", "Check transaction status"),
            "copyTxid" to listOf("複製交易 ID", "复制交易 ID", "Copy transaction ID"),
            "txSUBMITTING" to listOf("送出狀態未確定 · 正在查詢", "发送状态未确定 · 正在查询", "Submission interrupted · checking"),
            "txPENDING" to listOf("等待首次鏈上確認", "等待首次链上确认", "Awaiting first on-chain confirmation"),
            "txUNKNOWN" to listOf("廣播結果未確定 · 請勿重複送出", "广播结果未确定 · 请勿重复发送", "Submission uncertain · do not resend"),
            "txCONFIRMED" to listOf("首次鏈上確認成功", "首次链上确认成功", "First on-chain confirmation successful"),
            "txFAILED" to listOf("鏈上執行失敗", "链上执行失败", "On-chain execution failed"),
            "total" to listOf("資產總值", "资产总值", "TOTAL PORTFOLIO"),
            "knownSubtotal" to listOf("已取得資料的估值", "已取得数据的估值", "VALUE OF AVAILABLE DATA"),
            "unknownBalance" to listOf("餘額尚未取得", "余额尚未获取", "Balance unavailable"),
            "partialSync" to listOf("部分查詢未完成，已取得資料與上次持倉保留", "部分查询未完成，已取得数据与上次持仓保留", "Partial sync; available data and previous holdings retained"),
            "tronLimited" to listOf("TronGrid 拒絕或限制查詢。請在設定填入有效的 TronGrid API key，儲存後稍候再更新。", "TronGrid 拒绝或限制查询。请在设置填写有效的 TronGrid API key，保存后稍候再更新。", "TronGrid restricted this query. Add a valid TronGrid API key in Settings, save, then retry after the cooldown."),
            "binanceUnavailable" to listOf("無法取得 Binance 現貨報價；這不代表價格為零。請稍後更新並確認網路能連接 Binance。", "无法获取 Binance 现货报价；这不代表价格为零。请稍后更新并确认网络能连接 Binance。", "Binance Spot is unavailable; this does not mean the price is zero. Retry later and check network access to Binance."),
            "cardanoDaily" to listOf("Cardano 日常持倉每帳戶 24 小時同步一次，失敗也計算；交易準備與首次確認後另行更新。", "Cardano 日常持仓每账户 24 小时同步一次，失败也计算；交易准备与首次确认后另行更新。", "Cardano routine holdings sync once per account per 24h, including failures. Transaction preparation and first confirmation refresh separately."),
            "nextSync" to listOf("下次可同步持倉", "下次可同步持仓", "Next holdings sync available"),
            "spot" to listOf("Binance 現貨 · USDT", "Binance 现货 · USDT", "Binance Spot · USDT"),
            "refresh" to listOf("更新資產", "更新资产", "Refresh assets"),
            "refreshPrices" to listOf("更新價格 · 前景每 30 秒", "更新价格 · 前台每 30 秒", "Refresh prices · every 30s in foreground"),
            "updating" to listOf("正在更新…", "正在更新…", "Updating…"),
            "updated" to listOf("更新時間", "更新时间", "Updated"),
            "never" to listOf("尚未同步", "尚未同步", "Not synced yet"),
            "yourAssets" to listOf("持有資產", "持有资产", "Your assets"),
            "all" to listOf("全部", "全部", "All"),
            "emptyTitle" to listOf("從你的 Ledger 開始", "从你的 Ledger 开始", "Your Ledger. Your overview."),
            "emptyBody" to listOf("連接 Flex 並匯入公鑰，安全查看四鏈資產。私鑰始終留在裝置內。", "连接 Flex 并导入公钥，安全查看四链资产。私钥始终留在设备内。", "Connect Flex and import public keys to view four-chain holdings. Private keys stay on your device."),
            "connect" to listOf("連接 Ledger", "连接 Ledger", "Connect Ledger"),
            "demo" to listOf("預覽介面", "预览界面", "Preview interface"),
            "demoNotice" to listOf("示範資料 · 不代表真實持倉或即時價格", "示范数据 · 不代表真实持仓或实时价格", "Demo data · not real holdings or live prices"),
            "exitDemo" to listOf("離開預覽", "退出预览", "Exit preview"),
            "hiddenEmpty" to listOf("目前篩選條件沒有資產", "当前筛选条件下没有资产", "No assets match these filters"),
            "filter" to listOf("顯示選項", "显示选项", "Display options"),
            "missing" to listOf("無報價 · 估值 0", "无报价 · 估值 0", "No price · valued at 0"),
            "stale" to listOf("上次報價", "上次报价", "Last known price"),
            "unpriced" to listOf("等待報價", "等待报价", "Awaiting price"),
            "live" to listOf("Binance 現貨", "Binance 现货", "Binance Spot"),
            "hidden" to listOf("已隱藏", "已隐藏", "Hidden"),
            "hide" to listOf("隱藏此資產", "隐藏此资产", "Hide this asset"),
            "show" to listOf("恢復顯示", "恢复显示", "Show this asset"),
            "quantity" to listOf("持有數量", "持有数量", "Quantity"),
            "price" to listOf("單價（USDT）", "单价（USDT）", "Unit price (USDT)"),
            "value" to listOf("估值（USDT）", "估值（USDT）", "Value (USDT)"),
            "contract" to listOf("資產識別", "资产标识", "Asset identity"),
            "native" to listOf("主網原生幣", "主网原生币", "Mainnet native asset"),
            "private" to listOf("隱藏金額", "隐藏金额", "Hide amounts"),
            "reveal" to listOf("顯示金額", "显示金额", "Show amounts"),
            "accountEmpty" to listOf("尚未匯入帳戶", "尚未导入账户", "No accounts imported"),
            "accountHint" to listOf("每條鏈、每個帳戶需分別匯入。匯入後不需持續連接 Ledger。", "每条链、每个账户需分别导入。导入后无需保持 Ledger 连接。", "Import each chain and account separately. Ledger can be disconnected after import."),
            "import" to listOf("匯入公鑰", "导入公钥", "Import public key"),
            "remove" to listOf("移除帳戶", "移除账户", "Remove account"),
            "removeBody" to listOf("只移除手機內的唯讀資料，不影響鏈上資產。", "仅移除手机内的只读数据，不影响链上资产。", "Removes this phone's watch-only data. On-chain assets are unaffected."),
            "cancel" to listOf("取消", "取消", "Cancel"),
            "close" to listOf("關閉", "关闭", "Close"),
            "copy" to listOf("複製地址", "复制地址", "Copy address"),
            "path" to listOf("衍生路徑", "派生路径", "Derivation path"),
            "syncError" to listOf("持倉更新失敗，保留上次資料", "持仓更新失败，保留上次数据", "Balance update failed; previous data retained"),
            "priceError" to listOf("報價更新失敗，保留上次價格", "报价更新失败，保留上次价格", "Price update failed; previous prices retained"),
            "scanLimited" to listOf("地址驗證範圍有限；請增加掃描上限", "地址验证范围有限；请增加扫描上限", "Address validation capped; increase the scan limit"),
            "partial" to listOf("部分資料尚未取得，總額可能不完整", "部分数据尚未获取，总额可能不完整", "Some data is unavailable; total may be incomplete"),
            "usb" to listOf("使用 USB 連接", "使用 USB 连接", "Connect via USB"),
            "ble" to listOf("搜尋藍牙 Flex", "搜索蓝牙 Flex", "Find Flex via Bluetooth"),
            "disconnect" to listOf("中斷連線", "断开连接", "Disconnect"),
            "connection" to listOf("裝置連線", "设备连接", "Device connection"),
            "connectHint" to listOf("解鎖 Flex，開啟所選鏈的 App。使用可傳輸資料的 USB 線，或開啟 Flex 藍牙。", "解锁 Flex，打开所选链的 App。使用数据 USB 线，或开启 Flex 蓝牙。", "Unlock Flex and open the selected chain app. Use a USB data cable or enable Flex Bluetooth."),
            "permission" to listOf("需要藍牙權限才能搜尋及連線", "需要蓝牙权限才能搜索及连接", "Bluetooth permission is required to scan and connect"),
            "chain" to listOf("選擇主網", "选择主网", "Choose mainnet"),
            "accountName" to listOf("帳戶名稱（選填）", "账户名称（选填）", "Account name (optional)"),
            "index" to listOf("帳戶索引（0 起算）", "账户索引（从 0 开始）", "Account index (starts at 0)"),
            "approve" to listOf("確認匯入唯讀公鑰", "确认导入只读公钥", "Confirm public-key import"),
            "approveHint" to listOf("只讀取公鑰／地址，請在 Ledger 確認。Cardano 公鑰可能直接匯出，但仍會要求裝置顯示地址供你確認。", "仅读取公钥／地址，请在 Ledger 确认。Cardano 公钥可能直接导出，但仍会要求设备显示地址供你确认。", "Public keys and addresses only. Confirm on Ledger. Cardano key export may be silent, followed by an on-device address confirmation."),
            "appearance" to listOf("外觀與語言", "外观与语言", "Appearance & language"),
            "system" to listOf("跟隨系統", "跟随系统", "System"),
            "dark" to listOf("深色", "深色", "Dark"),
            "light" to listOf("淺色", "浅色", "Light"),
            "visibility" to listOf("資產顯示", "资产显示", "Asset visibility"),
            "zeroBalance" to listOf("隱藏零餘額", "隐藏零余额", "Hide zero balances"),
            "zeroBalanceHint" to listOf("以實際數量判斷，不受小數顯示影響", "按实际数量判断，不受小数显示影响", "Uses the actual quantity before rounding"),
            "zeroValue" to listOf("隱藏零估值", "隐藏零估值", "Hide zero values"),
            "zeroValueHint" to listOf("也會隱藏未找到 Binance 報價的資產", "也会隐藏未找到 Binance 报价的资产", "Also hides assets without a Binance quote"),
            "revealHidden" to listOf("顯示手動隱藏的資產", "显示手动隐藏的资产", "Reveal manually hidden assets"),
            "totalHint" to listOf("隱藏設定只影響列表，資產總值仍包含所有帳戶。", "隐藏设置仅影响列表，资产总值仍包含所有账户。", "Visibility affects the list; totals still include all accounts."),
            "data" to listOf("資料來源", "数据来源", "Data sources"),
            "dataHint" to listOf("價格：Binance 現貨。持倉：mempool.space、Blockstream、PublicNode、Blockscout、TronGrid、Koios／Blockfrost。查詢會將地址提供給對應服務。", "价格：Binance 现货。持仓：mempool.space、Blockstream、PublicNode、Blockscout、TronGrid、Koios／Blockfrost。查询会将地址发送给相应服务。", "Prices: Binance Spot. Holdings: mempool.space, Blockstream, PublicNode, Blockscout, TronGrid, Koios/Blockfrost. Queries disclose addresses to the respective service."),
            "cardanoKey" to listOf("Cardano mainnet Blockfrost API key", "Cardano mainnet Blockfrost API key", "Cardano mainnet Blockfrost API key"),
            "cardanoKeyHint" to listOf("有 key 時使用 Blockfrost；留空則使用公開 Koios API。", "有 key 时使用 Blockfrost；留空则使用公开 Koios API。", "Uses Blockfrost when a key is supplied; otherwise uses the public Koios API."),
            "tronKey" to listOf("TronGrid API key", "TronGrid API key", "TronGrid API key"),
            "tronKeyHint" to listOf("未填 key 容易遇到 HTTP 429。這是查詢服務的 key，與錢包私鑰無關。", "未填写 key 容易遇到 HTTP 429。这是查询服务的 key，与钱包私钥无关。", "Keyless queries may receive HTTP 429. This is a data-service key, separate from your wallet keys."),
            "createTronKey" to listOf("前往 TronGrid 建立 API key", "前往 TronGrid 创建 API key", "Create an API key on TronGrid"),
            "ethKey" to listOf("Alchemy API key（選填）", "Alchemy API key（选填）", "Alchemy API key (optional)"),
            "ethKeyHint" to listOf("Ethereum 代幣預設用 Blockscout；若服務受限，可填入 Alchemy key。", "Ethereum 代币默认使用 Blockscout；若服务受限，可填写 Alchemy key。", "Ethereum tokens use Blockscout by default. Supply an Alchemy key if access is restricted."),
            "keyHint" to listOf("儲存在 Android Keystore 加密檔案中；不會上傳到 GitHub。", "保存在 Android Keystore 加密文件中；不会上传到 GitHub。", "Stored in an Android Keystore-encrypted file; never uploaded to GitHub."),
            "save" to listOf("儲存設定", "保存设置", "Save settings"),
            "scan" to listOf("地址探索", "地址探索", "Address discovery"),
            "gap" to listOf("BTC 連續未使用地址數", "BTC 连续未使用地址数", "BTC unused-address gap"),
            "max" to listOf("每分支掃描／驗證上限", "每分支扫描／验证上限", "Scan/validation cap per branch"),
            "scanHint" to listOf("BTC：Native SegWit 收款與找零地址，依交易歷史掃描。ADA：Shelley base 地址，驗證付款公鑰。特殊路徑、Enterprise 地址、NFT 估價、DeFi 與質押部位暫不涵蓋。", "BTC：Native SegWit 收款与找零地址，按交易历史扫描。ADA：Shelley base 地址，验证支付公钥。暂不涵盖特殊路径、Enterprise 地址、NFT 估值、DeFi 与质押仓位。", "BTC: Native SegWit receive/change addresses scanned by history. ADA: Shelley base addresses with payment-key validation. Custom paths, enterprise addresses, NFT valuation, DeFi and staking positions are outside v0.1."),
            "security" to listOf("公鑰在手機，私鑰在 Ledger", "公钥在手机，私钥在 Ledger", "Public keys here. Private keys on Ledger."),
            "securityHint" to listOf("不要求助記詞、不匯入私鑰。交易需手機確認與 Ledger 實體核准，並在手機驗證簽名後廣播。這是獨立開源專案，與 Ledger 或 Binance 無隸屬關係。", "不要求助记词、不导入私钥。交易需手机确认与 Ledger 实体验证，并在手机验证签名后广播。这是独立开源项目，与 Ledger 或 Binance 无隶属关系。", "Never requests a recovery phrase or imports private keys. Transactions need phone review and physical Ledger approval, then local signature verification before broadcast. Independent of Ledger and Binance."),
            "validation" to listOf("請輸入範圍內的整數", "请输入范围内的整数", "Enter a whole number within the allowed range"),
            "balanceTime" to listOf("持倉時間", "持仓时间", "Balance timestamp"),
            "priceTime" to listOf("報價時間", "报价时间", "Price timestamp")
        )
    }
}
